num_words: 200000
num_chars: 200

max_words_seq: 40
max_chars_seq: 150

embeddings:
  - glove.840B.300d.txt
  - wiki-news-300d-1M.vec
  - paragram_300_sl999.txt
  - GoogleNews-vectors-negative300.bin
  - name: custom.vect
    size: 150
    window: 4
    min_count: 2

holdout: 0.2
holdout_seed: 211
folds: 5
folds_seed: 33
stratify_folds: true

model:
  words_dropout: 0.3
branches:
   global_features_network:
      input: words
      dropout: 0.3
      output: 16
   cnn:
      input: chars
      channels: [100,100,100,100,100]
      maxPools: [2,2,2,2,2]
      dropout: 0.3
      output: 16
   residual_gru_with_attention:
      input: words
      units: 100
      dropout: 0.2
      feature_count: 100
